# Generated by Django 4.1.5 on 2023-02-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.IntegerField(verbose_name='Course duration(weeks)'),
        ),
    ]
