# Generated by Django 4.1.5 on 2023-01-20 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(db_column='group_name', max_length=50, verbose_name='Group name')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('group_description', models.TextField(db_column='group_description', max_length=50, verbose_name='Group description')),
            ],
        ),
    ]
