# Generated by Django 4.1.5 on 2023-02-15 12:47

import core.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('group_name', models.CharField(db_column='group_name', max_length=50, verbose_name='Group name')),
                ('start_date', models.DateField(default=datetime.date.today, validators=[core.validators.validate_start_date])),
                ('end_date', models.DateField(default=datetime.datetime(2023, 5, 16, 12, 47, 39, 572672))),
                ('group_description', models.TextField(blank=True, db_column='group_description', max_length=50, null=True, verbose_name='Group description')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
