# Generated by Django 4.1.5 on 2023-02-11 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 13, 23, 45, 408420)),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_description',
            field=models.TextField(blank=True, db_column='group_description', max_length=50, null=True, verbose_name='Group description'),
        ),
    ]
