# Generated by Django 4.1.5 on 2023-01-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='groups',
        ),
    ]
