# Generated by Django 4.1.5 on 2023-02-15 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='group_teachers', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 16, 13, 27, 9, 72651)),
        ),
    ]
