# Generated by Django 4.1.5 on 2023-02-16 13:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('groups', '0003_group_teachers_alter_group_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 13, 30, 3, 384453)),
        ),
    ]
