# Generated by Django 4.1.5 on 2023-03-04 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_group_course_alter_group_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 2, 10, 47, 25, 54250)),
        ),
    ]
